---
services:
  code-server:
    image: $IMG_TITLE:$IMG_VERSION
    container_name: ${CONTAINER_NAME}_test
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=abc #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=$PROXY_DOMAIN #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
      - DOCKER_MODS=linuxserver/mods:universal-docker
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8444:8443
    restart: unless-stopped

