---
services:
  code-server:
    image: m3hran/code-server:0.2.1
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - PASSWORD=Diablo84! #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=abc #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code.sandboxz.com #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ./code-server/config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8444:8443
    restart: unless-stopped

